"""
Example input
"""
input ExampleInput {
  msg1: String
}

input UserInput {
  nome: String
  sobrenome: String
}

"""
Example result
"""
type ExampleResult {
  result1: String
}

type User {
  id: Int
  nome: String
  sobrenome: String
}

type Query {
  """
  # example 1
  """
  example1: String
  """
  # example 2
  """
  example2: ExampleResult

  """
  # example 3
  ## to call
  <code>
   example3(input: {msg1: "Rogerio"}) {
    result1
  }
  </code>
  """
  example3(input: ExampleInput): ExampleResult
  """
  # all msg
  """
  allMsg: [ExampleResult]
}

type Mutation {
  """
  Exp: example4(input:{msg1:"Olá pessoal"}) {
    result1
  }
  """
  example4(input: ExampleInput): ExampleResult
  """
  ### enviar mensagem para o RabbitMq
  """
  criateUser(inputUser: UserInput): User
}
